version: "3.9"

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ..:/app
    environment:
      - DATABASE_URL=sqlite:///./test.db
